# Generated by Django 5.1.1 on 2024-09-06 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0003_band_active_band_biography_band_genre_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="description",
            field=models.CharField(default="", max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="listing",
            name="sold",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="listing",
            name="type",
            field=models.CharField(
                choices=[
                    ("RECORDS", "Records"),
                    ("CLOTHING", "Clothing"),
                    ("POSTERS", "Posters"),
                    ("MISCELLANEOUS", "Miscellaneous"),
                ],
                default="MISCELLANEOUS",
                max_length=25,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="listing",
            name="year",
            field=models.IntegerField(default=2000),
            preserve_default=False,
        ),
    ]
