# Generated by Django 5.1.1 on 2024-09-06 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0005_listing_band"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="like_new",
            field=models.BooleanField(default=False),
        ),
    ]
