# Generated by Django 5.1.1 on 2024-09-06 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0006_listing_like_new"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listing",
            name="like_new",
        ),
    ]
